/** @file GLSLPostProcessor.h
 *  @brief Post-processor for GLSL source code generated by Slang.
 *
 *  Slang outputs Vulkan GLSL semantics (gl_VertexIndex, gl_InstanceIndex) which are
 *  incompatible with OpenGL's native GLSL compiler. This post-processor transforms
 *  the generated GLSL to use OpenGL-compatible builtins.
 *
 *  Architecture:
 *    - Zero-overhead: single-pass string replacement, no regex, no allocations during scan
 *    - Extensible: add new ReplacementRule entries to extend functionality
 *    - Compile-time config: replacement rules are constexpr arrays
 *
 *  Note: GL_KHR_vulkan_glsl extension does NOT help here because:
 *    1. It's designed for Vulkan SPIR-V generation, not OpenGL native GLSL compilation
 *    2. It REMOVES gl_VertexID/gl_InstanceID and ADDS gl_VertexIndex/gl_InstanceIndex
 *    3. OpenGL's GLSL compiler does not recognize gl_VertexIndex regardless of extensions
 *
 *  Namespace: miki::shader
 */
#pragma once

#include <array>
#include <cstdint>
#include <span>
#include <string>
#include <string_view>

namespace miki::shader {

    // =========================================================================
    // Replacement rule — compile-time defined string substitution
    // =========================================================================

    struct ReplacementRule {
        std::string_view pattern;
        std::string_view replacement;
    };

    // =========================================================================
    // Built-in rule sets
    // =========================================================================

    namespace glsl_rules {

        /** @brief Vulkan GLSL builtins -> OpenGL GLSL builtins.
         *
         *  Slang outputs Vulkan-style vertex/instance indices which OpenGL doesn't recognize.
         *  These are the only builtins that differ between Vulkan GLSL and OpenGL GLSL.
         */
        inline constexpr std::array<ReplacementRule, 2> kVulkanToOpenGLBuiltins = {{
            {.pattern = "gl_VertexIndex", .replacement = "gl_VertexID"},
            {.pattern = "gl_InstanceIndex", .replacement = "gl_InstanceID"},
        }};

    }  // namespace glsl_rules

    // =========================================================================
    // GLSLPostProcessor — single-pass multi-pattern string replacement
    // =========================================================================

    class GLSLPostProcessor {
       public:
        /** @brief Apply a set of replacement rules to GLSL source code.
         *
         *  Uses a simple linear scan with early-out on first character mismatch.
         *  For the small number of rules we have (2-4), this is faster than building
         *  an Aho-Corasick automaton or similar.
         *
         *  @param ioSource  GLSL source code (modified in-place if changes are made)
         *  @param iRules    Replacement rules to apply
         *  @return true if any replacements were made
         */
        template <size_t N>
        static auto Apply(std::string& ioSource, std::array<ReplacementRule, N> const& iRules) -> bool {
            return ApplyRules(ioSource, std::span<ReplacementRule const>(iRules));
        }

        /** @brief Apply Vulkan-to-OpenGL builtin replacements.
         *
         *  Convenience wrapper for the most common use case.
         */
        static auto ApplyVulkanToOpenGL(std::string& ioSource) -> bool {
            return Apply(ioSource, glsl_rules::kVulkanToOpenGLBuiltins);
        }

       private:
        static auto ApplyRules(std::string& ioSource, std::span<ReplacementRule const> iRules) -> bool {
            if (ioSource.empty() || iRules.empty()) {
                return false;
            }

            bool modified = false;

            // Process each rule sequentially. For 2-4 rules with short patterns,
            // this is more cache-friendly than interleaved multi-pattern matching.
            for (auto const& rule : iRules) {
                size_t pos = 0;
                while ((pos = ioSource.find(rule.pattern, pos)) != std::string::npos) {
                    ioSource.replace(pos, rule.pattern.size(), rule.replacement);
                    pos += rule.replacement.size();
                    modified = true;
                }
            }

            return modified;
        }
    };

}  // namespace miki::shader
