#!/usr/bin/env python3
"""Generate Kulla-Conty E_lut and E_avg LUT data for multi-scattering compensation.

Outputs a C++ header with constexpr float arrays:
  - kKullaContyE_lut[SIZE * SIZE]   (cosTheta x roughness -> directional albedo)
  - kKullaContyE_avg[SIZE]          (roughness -> average albedo)

Reference: Kulla & Conty 2017, "Revisiting Physically Based Shading at Imageworks"

Usage:
    python tools/generate_kulla_conty_lut.py > src/miki/render/KullaContyLutData.h
"""

import math
import sys
import struct

# LUT resolution — 64x64 for Phase 2 (sufficient accuracy, small binary).
# Can upgrade to 512x512 in Phase 3a if needed.
SIZE = 64
NUM_SAMPLES = 1024

def radical_inverse_vdc(bits: int) -> float:
    bits = ((bits << 16) | (bits >> 16)) & 0xFFFFFFFF
    bits = (((bits & 0x55555555) << 1) | ((bits & 0xAAAAAAAA) >> 1)) & 0xFFFFFFFF
    bits = (((bits & 0x33333333) << 2) | ((bits & 0xCCCCCCCC) >> 2)) & 0xFFFFFFFF
    bits = (((bits & 0x0F0F0F0F) << 4) | ((bits & 0xF0F0F0F0) >> 4)) & 0xFFFFFFFF
    bits = (((bits & 0x00FF00FF) << 8) | ((bits & 0xFF00FF00) >> 8)) & 0xFFFFFFFF
    return bits * 2.3283064365386963e-10

def hammersley(i: int, n: int):
    return (i / n, radical_inverse_vdc(i))

def importance_sample_ggx(xi_x: float, xi_y: float, roughness: float):
    a = roughness * roughness
    phi = 2.0 * math.pi * xi_x
    cos_theta = math.sqrt((1.0 - xi_y) / (1.0 + (a * a - 1.0) * xi_y + 1e-10))
    sin_theta = math.sqrt(max(0.0, 1.0 - cos_theta * cos_theta))
    hx = math.cos(phi) * sin_theta
    hy = math.sin(phi) * sin_theta
    hz = cos_theta
    return (hx, hy, hz)

def v_smith_ggx_correlated(ndotv: float, ndotl: float, roughness: float) -> float:
    """Height-correlated Smith GGX visibility: V = G / (4 * NoV * NoL).
    Matches shader V_SmithGGXCorrelated exactly."""
    a = roughness * roughness
    a2 = a * a
    lambda_v = ndotl * math.sqrt(ndotv * ndotv * (1.0 - a2) + a2)
    lambda_l = ndotv * math.sqrt(ndotl * ndotl * (1.0 - a2) + a2)
    return 0.5 / (lambda_v + lambda_l + 1e-10)

def integrate_e(cos_theta: float, roughness: float) -> float:
    """Integrate directional albedo E(cosTheta, roughness) via importance sampling."""
    if cos_theta < 1e-6:
        cos_theta = 1e-6

    Vdir = (math.sqrt(max(0.0, 1.0 - cos_theta * cos_theta)), 0.0, cos_theta)
    N = (0.0, 0.0, 1.0)

    result = 0.0
    for i in range(NUM_SAMPLES):
        xi = hammersley(i, NUM_SAMPLES)
        H = importance_sample_ggx(xi[0], xi[1], roughness)

        # L = reflect(-Vdir, H)
        vdh = Vdir[0] * H[0] + Vdir[1] * H[1] + Vdir[2] * H[2]
        L = (2.0 * vdh * H[0] - Vdir[0],
             2.0 * vdh * H[1] - Vdir[1],
             2.0 * vdh * H[2] - Vdir[2])

        ndotl = max(L[2], 0.0)
        ndotv = max(Vdir[2], 0.0)
        vdoth = max(vdh, 0.0)
        ndoth = max(H[2], 0.0)

        if ndotl > 0.0:
            # vis = G / (4*NoV*NoL), importance-sampled with GGX NDF.
            # PDF = D*NoH / (4*VoH), so integrand = F * G * VoH / (NoH * NoV)
            # = F * (4*NoV*NoL*vis) * VoH / (NoH * NoV)
            # = F * 4 * NoL * vis * VoH / NoH
            # With F0=1 (white furnace test):
            vis = v_smith_ggx_correlated(ndotv, ndotl, roughness)
            # Importance sampling weight: 4 * VoH * NoL * vis / NoH
            result += 4.0 * vdoth * ndotl * vis / (ndoth + 1e-10)
    return min(result / NUM_SAMPLES, 1.0)


def main():
    # Compute E_lut[SIZE * SIZE]
    e_lut = []
    for j in range(SIZE):
        roughness = (j + 0.5) / SIZE
        roughness = max(roughness, 0.01)
        for i in range(SIZE):
            cos_theta = (i + 0.5) / SIZE
            e = integrate_e(cos_theta, roughness)
            e_lut.append(e)
        progress = (j + 1) / SIZE * 100
        print(f"  E_lut row {j+1}/{SIZE} ({progress:.0f}%)", file=sys.stderr)

    # Compute E_avg[SIZE]
    e_avg = []
    for j in range(SIZE):
        roughness = (j + 0.5) / SIZE
        roughness = max(roughness, 0.01)
        # E_avg = 2 * integral_0^1 E(mu, roughness) * mu d_mu
        # Approximate with trapezoidal rule using E_lut row
        acc = 0.0
        for i in range(SIZE):
            cos_theta = (i + 0.5) / SIZE
            acc += e_lut[j * SIZE + i] * cos_theta * (1.0 / SIZE)
        e_avg.append(min(acc * 2.0, 1.0))

    # Convert to float16 for compact storage
    def to_f16_hex(val: float) -> str:
        """Convert float to uint16 representing IEEE 754 half-float."""
        b = struct.pack('e', val)
        u16 = struct.unpack('<H', b)[0]
        return f"0x{u16:04X}"

    # Output C++ header
    print("// AUTO-GENERATED by tools/generate_kulla_conty_lut.py -- DO NOT EDIT")
    print("// Kulla-Conty multi-scattering compensation LUT data")
    print(f"// Resolution: {SIZE}x{SIZE} (E_lut) + {SIZE}x1 (E_avg)")
    print(f"// Samples per texel: {NUM_SAMPLES}")
    print("#pragma once")
    print()
    print("#include <array>")
    print("#include <cstdint>")
    print()
    print("namespace miki::render {")
    print()
    print(f"inline constexpr uint32_t kKullaContyLutSize = {SIZE};")
    print()

    # E_lut as float16 (uint16_t) array — saves 50% binary size vs float
    print(f"// E_lut: directional albedo E(cosTheta, roughness)")
    print(f"// Layout: row-major, row = roughness, col = cosTheta")
    print(f"// Each value is IEEE 754 half-float stored as uint16_t")
    print(f"inline constexpr std::array<uint16_t, {SIZE * SIZE}> kKullaContyE_lut = {{")
    for j in range(SIZE):
        vals = []
        for i in range(SIZE):
            vals.append(to_f16_hex(e_lut[j * SIZE + i]))
        line = ", ".join(vals)
        comma = "," if j < SIZE - 1 else ""
        print(f"    {line}{comma}")
    print("};")
    print()

    print(f"// E_avg: average albedo E_avg(roughness)")
    print(f"inline constexpr std::array<uint16_t, {SIZE}> kKullaContyE_avg = {{")
    vals = [to_f16_hex(v) for v in e_avg]
    # Print in rows of 16
    for start in range(0, len(vals), 16):
        chunk = vals[start:start+16]
        line = ", ".join(chunk)
        comma = "," if start + 16 < len(vals) else ""
        print(f"    {line}{comma}")
    print("};")
    print()
    print("} // namespace miki::render")
    print()


if __name__ == "__main__":
    main()
