/**
 * @brief Build-time tool: precompile Slang shaders to WGSL for Emscripten builds.
 *
 * Usage: precompile_wgsl <output_dir>
 *
 * Compiles forward_vert.slang and forward_frag.slang to WGSL text,
 * writes them as C++ header files with embedded string literals.
 */

#include "miki/shader/SlangCompiler.h"
#include "miki/shader/ShaderTypes.h"

#include <cstdio>
#include <filesystem>
#include <fstream>
#include <string>
#include <string_view>

namespace fs = std::filesystem;

struct ShaderJob {
    fs::path sourcePath;
    std::string entryPoint;
    miki::shader::ShaderStage stage;
    std::string outputName;
    uint32_t pushConstantGroup = UINT32_MAX;
};

/** @brief Fix Slang's WGSL codegen for push constants.
 *
 * Slang emits `var<uniform> pc_0 : ...` without @binding/@group for
 * [[vk::push_constant]] variables. This function patches the WGSL to
 * add the correct bind group/binding attributes for WebGPU.
 */
static auto PatchPushConstantBinding(std::string& wgsl, uint32_t groupIndex) -> void {
    static constexpr std::string_view kBare = "var<uniform> pc_0";
    auto pos = wgsl.find(kBare);
    if (pos == std::string::npos) {
        return;
    }

    std::string replacement = "@binding(0) @group(" + std::to_string(groupIndex) + ") var<uniform> pc_0";
    wgsl.replace(pos, kBare.size(), replacement);
}

static auto WriteHeaderFile(
    const fs::path& outputDir, std::string_view headerName, std::string_view varName,
    const std::vector<uint8_t>& wgslData
) -> bool {
    auto path = outputDir / headerName;
    std::ofstream out(path, std::ios::binary);
    if (!out.is_open()) {
        std::fprintf(stderr, "Failed to open %s for writing\n", path.string().c_str());
        return false;
    }

    std::string wgsl(reinterpret_cast<const char*>(wgslData.data()), wgslData.size());

    out << "// Auto-generated by precompile_wgsl — DO NOT EDIT\n";
    out << "#pragma once\n\n";
    out << "inline constexpr const char* " << varName << " = R\"WGSL(\n";
    out << wgsl;
    if (!wgsl.empty() && wgsl.back() != '\n') {
        out << '\n';
    }
    out << ")WGSL\";\n";

    std::printf("  -> %s (%zu bytes WGSL)\n", path.string().c_str(), wgslData.size());
    return true;
}

auto main(int argc, char* argv[]) -> int {
    if (argc < 2) {
        std::fprintf(stderr, "Usage: precompile_wgsl <output_dir>\n");
        return 1;
    }

    fs::path outputDir(argv[1]);
    fs::create_directories(outputDir);

    auto compilerResult = miki::shader::SlangCompiler::Create();
    if (!compilerResult.has_value()) {
        std::fprintf(stderr, "Failed to create SlangCompiler\n");
        return 1;
    }
    auto& compiler = *compilerResult;

    auto shaderDir = fs::path(MIKI_RENDER_SHADER_DIR_LITERAL);
    auto commonDir = fs::path(MIKI_COMMON_SHADER_DIR_LITERAL);
    compiler.AddSearchPath(shaderDir);
    compiler.AddSearchPath(commonDir);

    ShaderJob jobs[] = {
        {shaderDir / "forward_vert.slang", "vertexMain", miki::shader::ShaderStage::Vertex, "forward_vert", 2},
        {shaderDir / "forward_frag.slang", "fragmentMain", miki::shader::ShaderStage::Fragment, "forward_frag"},
    };

    for (const auto& job : jobs) {
        std::printf("Compiling %s -> WGSL...\n", job.sourcePath.filename().string().c_str());

        miki::shader::ShaderCompileDesc desc{
            .sourcePath = job.sourcePath,
            .entryPoint = job.entryPoint,
            .stage = job.stage,
            .target = miki::shader::ShaderTarget::WGSL,
        };

        auto blob = compiler.Compile(desc);
        if (!blob.has_value()) {
            std::fprintf(stderr, "  FAILED (error %d)\n", static_cast<int>(blob.error()));
            return 1;
        }

        auto& blobData = blob->data;

        if (job.pushConstantGroup != UINT32_MAX) {
            std::string wgsl(reinterpret_cast<const char*>(blobData.data()), blobData.size());
            PatchPushConstantBinding(wgsl, job.pushConstantGroup);
            blobData.assign(
                reinterpret_cast<const uint8_t*>(wgsl.data()),
                reinterpret_cast<const uint8_t*>(wgsl.data() + wgsl.size())
            );
            std::printf("  Patched push constant -> @group(%u)\n", job.pushConstantGroup);
        }

        auto headerName = job.outputName + "_wgsl.h";

        // Build variable name: "forward_vert" -> "kForward_vert_WGSL"
        std::string varName = "k";
        bool capitalizeNext = true;
        for (char c : job.outputName) {
            if (c == '_') {
                varName += c;
                capitalizeNext = true;
            } else if (capitalizeNext) {
                varName += static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
                capitalizeNext = false;
            } else {
                varName += c;
            }
        }
        varName += "_WGSL";

        if (!WriteHeaderFile(outputDir, headerName, varName, blobData)) {
            return 1;
        }
    }

    std::printf("All shaders precompiled successfully.\n");
    return 0;
}
